{"name": "test_count_endpoint[monthly-kolonka-active]", "status": "broken", "statusDetails": {"message": "TypeError: 'int' object is not callable", "trace": "api_context = <playwright._impl._fetch.APIRequestContext object at 0x000002117FD9D010>, status = 'active', tag = 'kolonka', date_type = 'monthly'\n\n    @pytest.mark.parametrize(\"status\", STATUSES)\n    @pytest.mark.parametrize(\"tag\", TAGS)\n    @pytest.mark.parametrize(\"date_type\", DATE_TYPES)\n    def test_count_endpoint(api_context, status, tag, date_type):\n        count_api = StatisticsAPI(api_context)\n        params = {\n            **DEFAULT_PARAMS,\n            \"status\": status,\n            \"tag\": tag,\n            \"date_type\": date_type\n        }\n        response = count_api.get_counts(**params)\n>       assert response.status == 200 (\n            f\"Unexpected status code: {response.status} for \"\n            f\"status={status}, tag={tag}, date_type={date_type}\"\n        )\nE       TypeError: 'int' object is not callable\n\ntest_products.py:171: TypeError"}, "parameters": [{"name": "date_type", "value": "'monthly'"}, {"name": "tag", "value": "'kolonka'"}, {"name": "status", "value": "'active'"}], "start": 1759751427822, "stop": 1759751427908, "uuid": "731561b0-d741-4035-9405-a893edbcc948", "historyId": "8cfd272738beb7dff1986ee9cb98f495", "testCaseId": "a1a25b2e255c1aeacc61b88f5be73e55", "fullName": "tests.test_products#test_count_endpoint", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_products"}, {"name": "host", "value": "PC-2993"}, {"name": "thread", "value": "23396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_products"}], "titlePath": ["tests", "test_products.py"]}