{"name": "test_count_endpoint[current-kolonka-inactive]", "status": "broken", "statusDetails": {"message": "TypeError: 'int' object is not callable", "trace": "api_context = <playwright._impl._fetch.APIRequestContext object at 0x000002117FD9D010>, status = 'inactive', tag = 'kolonka', date_type = 'current'\n\n    @pytest.mark.parametrize(\"status\", STATUSES)\n    @pytest.mark.parametrize(\"tag\", TAGS)\n    @pytest.mark.parametrize(\"date_type\", DATE_TYPES)\n    def test_count_endpoint(api_context, status, tag, date_type):\n        count_api = StatisticsAPI(api_context)\n        params = {\n            **DEFAULT_PARAMS,\n            \"status\": status,\n            \"tag\": tag,\n            \"date_type\": date_type\n        }\n        response = count_api.get_counts(**params)\n>       assert response.status == 200 (\n            f\"Unexpected status code: {response.status} for \"\n            f\"status={status}, tag={tag}, date_type={date_type}\"\n        )\nE       TypeError: 'int' object is not callable\n\ntest_products.py:171: TypeError"}, "parameters": [{"name": "date_type", "value": "'current'"}, {"name": "tag", "value": "'kolonka'"}, {"name": "status", "value": "'inactive'"}], "start": 1759751426631, "stop": 1759751426708, "uuid": "7ae8db2e-baf0-41ff-b6f5-53bb1e5a279a", "historyId": "169d9fe527e4fe594e2f020fb2841236", "testCaseId": "a1a25b2e255c1aeacc61b88f5be73e55", "fullName": "tests.test_products#test_count_endpoint", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_products"}, {"name": "host", "value": "PC-2993"}, {"name": "thread", "value": "23396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_products"}], "titlePath": ["tests", "test_products.py"]}