{"name": "test_login_invalid_credentials", "status": "broken", "statusDetails": {"message": "TypeError: AuthAPI.login() got an unexpected keyword argument 'expiresInMins'. Did you mean 'expires_in'?", "trace": "api_context = <playwright._impl._fetch.APIRequestContext object at 0x000002A9FB1F4C20>\n\n    @pytest.mark.api\n    def test_login_invalid_credentials(api_context):\n        login_api = AuthAPI(api_context)\n>       response = login_api.login(\n            username=\"invaliduser\",\n            password=\"wrongpass\",\n            expiresInMins=30\n        )\nE       TypeError: AuthAPI.login() got an unexpected keyword argument 'expiresInMins'. Did you mean 'expires_in'?\n\ntest_login.py:29: TypeError"}, "start": 1760088658272, "stop": 1760088658272, "uuid": "8e803736-6f22-4e1f-a1b6-6aec491a297b", "historyId": "ba4e553d88338b4c3aa782986d363389", "testCaseId": "ba4e553d88338b4c3aa782986d363389", "fullName": "tests.test_login#test_login_invalid_credentials", "labels": [{"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "PC-2993"}, {"name": "thread", "value": "18572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "titlePath": ["tests", "test_login.py"]}